/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wondertek_video_appmanager_AppManager_MyReceiver */

#ifndef _Included_com_wondertek_video_appmanager_AppManager_MyReceiver
#define _Included_com_wondertek_video_appmanager_AppManager_MyReceiver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
