/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.wondertek.activity;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int contents_text=0x7f050001;
        public static final int encode_view=0x7f050002;
        public static final int help_button_view=0x7f050003;
        public static final int help_view=0x7f050004;
        public static final int possible_result_points=0x7f050005;
        public static final int result_image_border=0x7f050006;
        public static final int result_minor_text=0x7f050007;
        public static final int result_points=0x7f050008;
        public static final int result_text=0x7f050009;
        public static final int result_view=0x7f05000a;
        public static final int sbc_header_text=0x7f05000b;
        public static final int sbc_header_view=0x7f05000c;
        public static final int sbc_layout_view=0x7f05000e;
        public static final int sbc_list_item=0x7f05000d;
        public static final int sbc_page_number_text=0x7f05000f;
        public static final int sbc_snippet_text=0x7f050010;
        public static final int share_text=0x7f050011;
        public static final int status_text=0x7f050012;
        public static final int transparent=0x7f050013;
        public static final int transparent_background=0x7f050000;
        public static final int viewfinder_frame=0x7f050014;
        public static final int viewfinder_laser=0x7f050015;
        public static final int viewfinder_mask=0x7f050016;
    }
    public static final class drawable {
        public static final int ar_mobile=0x7f020000;
        public static final int dingwei=0x7f020001;
        public static final int gdmap_btnloc_nor=0x7f020002;
        public static final int gdmap_btnloc_press=0x7f020003;
        public static final int gdmap_duoyun=0x7f020004;
        public static final int gdmap_fax_position=0x7f020005;
        public static final int gdmap_iconlocr_nor=0x7f020006;
        public static final int gdmap_iconmarka=0x7f020007;
        public static final int gdmap_iconmarkb=0x7f020008;
        public static final int gdmap_iconmarkc=0x7f020009;
        public static final int gdmap_iconmarkd=0x7f02000a;
        public static final int gdmap_iconmarke=0x7f02000b;
        public static final int gdmap_iconmarkf=0x7f02000c;
        public static final int gdmap_iconmarkg=0x7f02000d;
        public static final int gdmap_iconmarkh=0x7f02000e;
        public static final int gdmap_iconmarki=0x7f02000f;
        public static final int gdmap_iconmarkj=0x7f020010;
        public static final int gdmap_leiyu=0x7f020011;
        public static final int gdmap_location=0x7f020012;
        public static final int gdmap_qing=0x7f020013;
        public static final int gdmap_qp_bg=0x7f020014;
        public static final int gdmap_switch_icon=0x7f020015;
        public static final int gdmap_tip_pointer_button=0x7f020016;
        public static final int gdmap_tip_pointer_button_ex=0x7f020017;
        public static final int gdmap_tip_pointer_button_normal=0x7f020018;
        public static final int gdmap_tip_pointer_button_selected=0x7f020019;
        public static final int gdmap_wu=0x7f02001a;
        public static final int gdmap_xue=0x7f02001b;
        public static final int gdmap_yu=0x7f02001c;
        public static final int ico_more=0x7f02001d;
        public static final int ico_route=0x7f02001e;
        public static final int icon=0x7f02001f;
        public static final int launcher_icon=0x7f020020;
        public static final int line_y=0x7f020021;
        public static final int loading=0x7f020022;
        public static final int mc_bg=0x7f020023;
        public static final int mcsj_bg=0x7f020024;
        public static final int notification=0x7f020025;
        public static final int pop=0x7f020026;
    }
    public static final class id {
        public static final int ImageButtonRight=0x7f060026;
        public static final int LinearLayoutPoi=0x7f060023;
        public static final int LinearLayoutPopup=0x7f060022;
        public static final int PoiAddress=0x7f060025;
        public static final int PoiName=0x7f060024;
        /**  Messages IDs 
         */
        public static final int auto_focus=0x7f060000;
        public static final int barcode_image_view=0x7f06000e;
        public static final int btn_left=0x7f06001e;
        public static final int btn_right=0x7f060020;
        public static final int contents_supplement_text_view=0x7f060018;
        public static final int contents_text_view=0x7f060017;
        public static final int decode=0x7f060001;
        public static final int decode_failed=0x7f060002;
        public static final int decode_succeeded=0x7f060003;
        public static final int format_text_view=0x7f060010;
        public static final int format_text_view_label=0x7f06000f;
        public static final int item_detail_btn=0x7f06001d;
        public static final int item_name=0x7f06001c;
        public static final int item_name_ex=0x7f06001f;
        public static final int launch_product_query=0x7f060004;
        public static final int map_location_btn=0x7f060021;
        public static final int meta_text_view=0x7f060016;
        public static final int meta_text_view_label=0x7f060015;
        public static final int preview_view=0x7f06000b;
        public static final int quit=0x7f060005;
        public static final int restart_preview=0x7f060006;
        public static final int result_button_view=0x7f060019;
        public static final int result_view=0x7f06000d;
        public static final int return_scan_result=0x7f060007;
        public static final int search_book_contents_failed=0x7f060008;
        public static final int search_book_contents_succeeded=0x7f060009;
        public static final int shopper_button=0x7f06001a;
        public static final int status_view=0x7f06001b;
        public static final int textView1=0x7f06000a;
        public static final int time_text_view=0x7f060014;
        public static final int time_text_view_label=0x7f060013;
        public static final int title=0x7f060028;
        public static final int type_text_view=0x7f060012;
        public static final int type_text_view_label=0x7f060011;
        public static final int viewfinder_view=0x7f06000c;
        public static final int weather=0x7f060027;
    }
    public static final class layout {
        public static final int ar_interface_overlay=0x7f030000;
        public static final int capture=0x7f030001;
        public static final int gdmap_popview_item=0x7f030002;
        public static final int gdmap_popview_item_ex=0x7f030003;
        public static final int gdmap_popview_location=0x7f030004;
        public static final int gdmap_popview_point=0x7f030005;
        public static final int gdmap_popview_weather=0x7f030006;
        public static final int progress_medium=0x7f030007;
    }
    public static final class raw {
        public static final int beep=0x7f040000;
    }
    public static final class string {
        public static final int apk_id=0x7f070001;
        public static final int app_name=0x7f070000;
        public static final int button_add_calendar=0x7f07002b;
        public static final int button_add_contact=0x7f07002c;
        public static final int button_book_search=0x7f07002d;
        public static final int button_custom_product_search=0x7f07002e;
        public static final int button_dial=0x7f07002f;
        public static final int button_email=0x7f070030;
        public static final int button_get_directions=0x7f070031;
        public static final int button_google_shopper=0x7f070023;
        public static final int button_mms=0x7f070032;
        public static final int button_ok=0x7f070024;
        public static final int button_open_browser=0x7f070033;
        public static final int button_product_search=0x7f070034;
        public static final int button_search_book_contents=0x7f070035;
        public static final int button_share_by_email=0x7f070036;
        public static final int button_share_by_sms=0x7f070037;
        public static final int button_show_map=0x7f070038;
        public static final int button_sms=0x7f070039;
        public static final int button_web_search=0x7f07003a;
        public static final int common_cancel=0x7f070009;
        public static final int common_ok=0x7f070008;
        public static final int contentTitle=0x7f070046;
        public static final int debug=0x7f070003;
        public static final int error_cmcc_disconnected=0x7f07000c;
        public static final int error_cmcc_not_exist=0x7f07000d;
        public static final int error_code=0x7f070021;
        public static final int error_login1=0x7f070011;
        public static final int error_login15=0x7f070016;
        public static final int error_login17=0x7f070017;
        public static final int error_login2=0x7f070012;
        public static final int error_login26=0x7f070018;
        public static final int error_login3=0x7f070013;
        public static final int error_login40=0x7f070019;
        public static final int error_login7=0x7f070014;
        public static final int error_login8=0x7f070015;
        public static final int error_login99=0x7f07001a;
        public static final int error_login_failed=0x7f07000e;
        public static final int error_login_network=0x7f070010;
        public static final int error_logout11=0x7f07001d;
        public static final int error_logout18=0x7f07001e;
        public static final int error_logout7=0x7f07001b;
        public static final int error_logout9=0x7f07001c;
        public static final int error_logout99=0x7f07001f;
        public static final int error_logout_failed=0x7f070020;
        public static final int error_logout_network=0x7f070022;
        public static final int error_manual_disabled=0x7f07000a;
        public static final int error_sdcard_unavaiable=0x7f07000f;
        public static final int error_wifi_disabled=0x7f07000b;
        public static final int gdmap_address=0x7f07004f;
        public static final int gdmap_china=0x7f070050;
        public static final int gdmap_error=0x7f070049;
        public static final int gdmap_location_error=0x7f070047;
        public static final int gdmap_locationing=0x7f070048;
        public static final int gdmap_progress_msg=0x7f07004d;
        public static final int gdmap_progress_msg1=0x7f07004e;
        public static final int gdmap_provider_error=0x7f07004c;
        public static final int gdmap_route_error=0x7f07004b;
        public static final int gdmap_search_endmsg1=0x7f070053;
        public static final int gdmap_search_endmsg2=0x7f070054;
        public static final int gdmap_search_startmsg1=0x7f070051;
        public static final int gdmap_search_startmsg2=0x7f070052;
        public static final int gdmap_searching=0x7f07004a;
        public static final int install_res_live=0x7f070007;
        public static final int msg_camera_framework_bug=0x7f070025;
        public static final int msg_default_format=0x7f070026;
        public static final int msg_default_meta=0x7f070027;
        public static final int msg_default_status=0x7f070028;
        public static final int msg_default_time=0x7f070029;
        public static final int msg_default_type=0x7f07002a;
        public static final int platform=0x7f070002;
        public static final int result_address_book=0x7f07003b;
        public static final int result_calendar=0x7f07003c;
        public static final int result_email_address=0x7f07003d;
        public static final int result_geo=0x7f07003e;
        public static final int result_isbn=0x7f07003f;
        public static final int result_product=0x7f070040;
        public static final int result_sms=0x7f070041;
        public static final int result_tel=0x7f070042;
        public static final int result_text=0x7f070043;
        public static final int result_uri=0x7f070044;
        public static final int tickerText=0x7f070045;
        public static final int update_res_name=0x7f070005;
        public static final int update_res_ver_json=0x7f070006;
        public static final int update_server=0x7f070004;
    }
    public static final class style {
        public static final int Transparent=0x7f080000;
    }
}
