/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wondertek_video_appmanager_AppManager */

#ifndef _Included_com_wondertek_video_appmanager_AppManager
#define _Included_com_wondertek_video_appmanager_AppManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wondertek_video_appmanager_AppManager_STATE_IDLE
#define com_wondertek_video_appmanager_AppManager_STATE_IDLE 0L
#undef com_wondertek_video_appmanager_AppManager_STATE_INSTALLING
#define com_wondertek_video_appmanager_AppManager_STATE_INSTALLING 1L
#undef com_wondertek_video_appmanager_AppManager_STATE_UNINSTALLING
#define com_wondertek_video_appmanager_AppManager_STATE_UNINSTALLING 2L
#undef com_wondertek_video_appmanager_AppManager_SHARE_TEXT
#define com_wondertek_video_appmanager_AppManager_SHARE_TEXT 1L
#undef com_wondertek_video_appmanager_AppManager_SHARE_IMAGE
#define com_wondertek_video_appmanager_AppManager_SHARE_IMAGE 2L
/*
 * Class:     com_wondertek_video_appmanager_AppManager
 * Method:    applyPatchToOldApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wondertek_video_appmanager_AppManager_applyPatchToOldApk
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
